export const exercise = [
  {exerciseName: 'jumping jacks'},
  {exerciseName: 'push Ups'},
  {exerciseName: 'Sit up'},
  {exerciseName: 'pull ups'},
  {exerciseName: 'squats'},
];

export const loseWeight = [
  {
    level: 'Beginner',
    plan: [
      {
        day: 1,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
        time: [60, 5, 30, 5, 60, 5, 60],
      },
      {
        day: 2,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
      },
      {
        day: 3,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
      },
      {
        day: 4,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
      },
      {
        day: 5,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
      },
      {
        day: 6,
        routine: [
          'jumping jacks',
          'rest',
          'squats',
          'rest',
          'sit up',
          'rest',
          'pull ups',
        ],
      },
      {
        day: 7,
        routine: ['rest'],
      },
    ],
  },
  {
    level: 'Intermidiate',
    plan: [
      {
        day: 1,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 2,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 3,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 4,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 5,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 6,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 7,
        routine: ['rest'],
      },
    ],
  },
  {
    level: 'Advanced',
    plan: [
      {
        day: 1,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 2,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 3,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 4,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 5,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 6,
        routine: ['jumping jacks', 'squats', 'sit up', 'pull ups'],
      },
      {
        day: 7,
        routine: ['rest'],
      },
    ],
  },
];

export const loseWeightBeginner = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const loseWeightIntermidiate = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 5},
      {name: 'squats', time: 30},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 30},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const loseWeightAdvanced = [
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 120},
      {name: 'rest', time: 5},
      {name: 'squats', time: 60},
      {name: 'rest', time: 5},
      {name: 'sit up', time: 120},
      {name: 'rest', time: 5},
      {name: 'pull ups', time: 240},
      {name: 'strecth', time: 20},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const buildMusclesBeginner = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const buildMusclesIntermidiate = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const buildMusclesAdvanced = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const keepFitBeginner = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const keepFitIntermidiate = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];

export const keepFitAdvanced = [
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: [
      {name: 'jumping jacks', time: 60},
      {name: 'rest', time: 10},
      {name: 'sit up', time: 60},
      {name: 'rest', time: 10},
      {name: 'pull ups', time: 60},
      {name: 'rest', time: 10},
      {name: 'squats', time: 30},
      {name: 'rest', time: 10},
      {name: 'push ups', time: 60},
      {name: 'stretch', time: 10},
    ],
  },
  {
    routine: ['rest'],
  },
];
